version: '3.8'
services:
  app:
    build: ./app
    container_name: demo-app
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=demo_db
    ports:
      - "8081:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: demo-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=demo_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=exporter:exporter_password@(mysql:3306)/
    depends_on:
      - mysql
    ports:
      - "9104:9104"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    pid: "host"
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=admin@gmail.com
      - GF_SMTP_PASSWORD="your passdord"
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=admin@gmail.com    
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  mysql-data:
  prometheus-data:
  grafana-data:
